apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service-deployment
  labels:
    app: todo-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      containers:
      - name: todo-service
        image: your-docker-repo/todo-service:latest  # Replace with your Docker image
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: "mongodb://mongo-service:27017/todos"  # MongoDB connection string
